### ISSUE TITLE
Create Input Fields for Resume Template

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/resume-builder#2]
![image](https://github.com/user-attachments/assets/73679043-98a8-43e7-8676-b202aeddc417)

Create a responsive form with various input fields for all the sections in the resume template.
The input form should match the structure of the template, allowing users to fill out their details easily.
Ensure that the input fields dynamically populate the resume template, maintaining the formatting.
Sections for Input Fields:

Personal Information:

Name (Text Input)
Roll Number (Text Input)
Course - Branch (Text Input)
Contact Number (Phone Input)
Email (Email Input)
GitHub Profile (URL Input)
LinkedIn Profile (URL Input)
Education:

Degree/Certificate (Text Input)
Institute/Board (Text Input)
CGPA/Percentage (Text Input)
Year (Number Input)
Experience:

Experience Title (Text Input)
Designation (Text Input)
Timeline (Date Range Input)
Description (Textarea/Multiple Input)
Projects:

Project Name (Text Input)
Project Type (Text Input)
Timeline (Date Range Input)
GitHub Link (URL Input)
Description (Textarea/Multiple Input)
Technical Skills:

Category (Text Input)
Skill List (Text Input, comma-separated values)
Key Courses Taken:

Category (Text Input)
Course Name (Text Input)
Positions of Responsibility:

Title (Text Input)
Club/Fest/Board (Text Input)
Timeline (Date Range Input)
Description (Textarea)
Achievements:

Title (Text Input)
Description (Textarea)
Year (Number Input)
Features:

Use React to create input forms.
Implement Tailwind CSS for styling the form, keeping it simple and responsive.
Bind the input fields to dynamically update the sections of the resume.
Add validation (e.g., required fields like Name, Email, etc.).
Make sure that long descriptions do not break the layout.
Ensure mobile responsiveness.

**Comment by devjainofficial** [comment]
@Ashmit-Verma Can You please assign me this task.

**Comment by Ashmit-Verma** [comment]
@devjainofficial assigned to you

**Comment by devjainofficial** [comment]
Sorry for the misunderstanding.

Please check the #3 


![image](https://github.com/user-attachments/assets/a7995c1c-6fff-47db-9837-258aff79c89d)
<img width="758" alt="image" src="https://github.com/user-attachments/assets/4874e590-4401-4231-8c7b-cc30e9fc1bd7">
You will get the response in Json format
